### ISSUE TITLE
Crashes on mismatched docstring delimiters

### ISSUE THREAD

**Issue by cjwatson** [keewis/blackdoc#131]
Thanks for `blackdoc`!  I'm looking forward to taming our wild-west of doctests a bit.

Code such as this in a doctest confuses `blackdoc`:

```
    >>> class IMyNewBuildFarmJob(IBuildFarmJob):
    ...     "Normally defines job-type specific database fields."""
```

This is technically valid Python (it parses as a `"..."`-delimited string with an empty string concatenated to it), though it's clearly a mistake and I'm going to fix it in our code.  Nevertheless, `blackdoc` shouldn't crash on it.

```
Traceback (most recent call last):
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/bin/blackdoc", line 8, in <module>
    sys.exit(main())
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/__main__.py", line 522, in main
    sys.exit(process(args))
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/__main__.py", line 338, in process
    changed_sources = {
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/__main__.py", line 339, in <dictcomp>
    source: action(source, mode, **action_kwargs) for source in sorted(sources)
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/__main__.py", line 157, in format_and_overwrite
    new_content = "\n".join(format_lines(lines, mode))
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/blacken.py", line 71, in blacken
    reformatted = reformat_code(
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/formats/__init__.py", line 33, in reformat_code
    reformatted = func(line_unit, **parameters)
  File "/home/cjwatson/.cache/pre-commit/repon469pkud/py_env-python3/lib/python3.10/site-packages/blackdoc/formats/doctest.py", line 125, in reformatting_func
    reformatted = reformatted.replace(current_quotes, docstring_quotes)
TypeError: replace() argument 1 must be str, not None
```

**Comment by keewis** [comment]
Thanks for the report, @cjwatson, and sorry for closing this without an answer.

The test suite is fairly minimal at the moment, so I'm not surprised that some of the edge cases result in crashes. I'd love to use a fuzzer like `hypothesis` to find all those, but until then feel free to keep the edge cases coming!
