### ISSUE TITLE
`TokenError` on second run

### ISSUE THREAD

**Issue by jugmac00** [keewis/blackdoc#142]
I tried running `blackdoc` via `pre-commit` on https://launchpad.net/launchpad

```
-   repo: https://github.com/keewis/blackdoc
    rev: v0.3.6
    hooks:
    -   id: blackdoc
        files: .*\.rst
        exclude: ^doc/.*
```

Running `pre-commit run blackdoc --all-files` succeeds the first time, but fails on the second run with the following traceback...

```
❯ pre-commit run blackdoc --all-files
blackdoc.................................................................Failed
- hook id: blackdoc
- exit code: 1

Traceback (most recent call last):
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/bin/blackdoc", line 8, in <module>
    sys.exit(main())
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/__main__.py", line 375, in main
    sys.exit(process(args))
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/__main__.py", line 162, in process
    changed_sources = {
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/__main__.py", line 163, in <dictcomp>
    source: action(source, mode, **action_kwargs) for source in sorted(sources)
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/__main__.py", line 35, in format_and_overwrite
    new_content = "\n".join(format_lines(lines, mode))
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/blacken.py", line 36, in blacken
    indentation_depth, parameters, code = extract_code(line_unit, code_format)
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/formats/__init__.py", line 24, in extract_code
    parameters, extracted = func(dedented)
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/formats/doctest.py", line 122, in extraction_func
    docstring_quotes = detect_docstring_quotes(extracted_line)
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/formats/doctest.py", line 90, in detect_docstring_quotes
    string_tokens = list(tokenize(line))
  File "/home/jugmac00/.cache/pre-commit/repouw1mizj3/py_env-python3/lib/python3.8/site-packages/blackdoc/formats/doctest.py", line 62, in <genexpr>
    return (
  File "/usr/lib/python3.8/tokenize.py", line 461, in _tokenize
    raise TokenError("EOF in multi-line string", strstart)
tokenize.TokenError: ('EOF in multi-line string', (4, 8))
```

I had no time yet to create a minimal reproducer, but will create one if the above traceback does not give any clue what happens.

**Comment by jugmac00** [comment]
## (more) minimal reproducer

```
some text:

    >>> config.push('statsd_test', dedent('''
    ...     [statsd]
    ...     environment: test
    ...     '''))
```

turns into

```
    >>> config.push(
    ...     "statsd_test",
    ...     dedent(
    ...         '''
    ...     [statsd]
    ...     environment: test
    ...     """
    ...     ),
    ... )
```

and then crashes on the next run.

**Comment by jugmac00** [comment]
Basically the issue is...

```
'''foo'''
```
=>
'''foo"""
```

**Comment by keewis** [comment]
so there's two things going on: the first one being that I forgot to appropriately handle `TokenError` (I'm going to silence it, I think, because `black` would raise in that case as well, and with a nicer error message), and the second one that the triple-quote reconstruction algorithm is now completely broken: notice how the second `"""` was not changed to `'''` because it is now on a different line (see also #139).

For now you can pin `blackdoc` to 0.3.4, which should work because in that version we just replace every sequence of three quotes with the other type of quotes (`"""` → `'''` or `'''` → `"""`).

In any case, I'm currently trying to figure out how to both detect the technically valid `"some string"""` *and* work in the general case.

**Comment by jugmac00** [comment]
Thanks for getting back to me.

As this issue only affected 11 files, I decided to still use the latest version, but to manually convert the triple single quotes to double quotes.

Thanks for looking into the issue and thanks a lot of providing this tool!
